server:
  port: 8072
  error:
    include-message: always
    include-binding-errors: always

pasive:
  card: "http://host.docker.internal:8022"

spring:
  data:
    mongodb:
      uri: mongodb+srv://sa:R35rPvm0XFgR8dIh@walter.iyabt.mongodb.net/bootcamp?retryWrites=true&w=majority

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
